### ISSUE TITLE
Add style choices as option or config file

### ISSUE THREAD

**Issue by murrayo** [murrayo/yape#13]
I find the dot chart is sometimes better for analysing issues- its a bit like an x-ray view when there are outliers; where a line graph will draw a line to something and can give a wrong impression of peaks a few stray dots is often clearer and better context. Which leads to the path of choosing chart styles. Whether this can be passed as a config file so someone can set up their favourite colour schemes etc or whether we just have a few basic switches we can chat about.

**Comment by kazamatzuri** [comment]
agreed. we have the infrastructure layed out for putting options in the config file. following the example of the output graph size should be pretty straightforward

**Comment by kazamatzuri** [comment]
6f80aaf
We can discuss adding this as command line option as well if the config file way is not sufficient.
I would just pass a config with '--config dots.yml' where i have that setup ...
