### ISSUE TITLE
Building image locally fails

### ISSUE THREAD

**Issue by pisani** [murrayo/yape#16]
Building a docker image locally fails:

spisani@ubuntu:~/Documents/Yape/yape$ docker build -t yape2 .
Sending build context to Docker daemon  1.977MB
Step 1/4 : FROM python:3
3: Pulling from library/python
741437d97401: Pull complete 
34d8874714d7: Pull complete 
0a108aa26679: Pull complete 
7f0334c36886: Pull complete 
49ea0d2b5c48: Pull complete 
f70a6aa0163b: Pull complete 
4b9b78e41a03: Pull complete 
9e9b4c0fa8a2: Pull complete 
c55a3146e261: Pull complete 
Digest: sha256:235896d5fa8b80e374b0dedd35a67732ef131a322cc7c975da5e347496967bcc
Status: Downloaded newer image for python:3
 ---> 5850a68e164d
Step 2/4 : RUN pip install -e git+https://github.com/murrayo/yape.git#egg=yape
 ---> Running in c2ad68655d67
Obtaining yape from git+https://github.com/murrayo/yape.git#egg=yape
  Cloning https://github.com/murrayo/yape.git to /src/yape
Collecting pytz==2018.5 (from yape)
  Downloading https://files.pythonhosted.org/packages/30/4e/27c34b62430286c6d59177a0842ed90dc789ce5d1ed740887653b898779a/pytz-2018.5-py2.py3-none-any.whl (510kB)
Collecting matplotlib==2.2.3 (from yape)
  Downloading https://files.pythonhosted.org/packages/52/46/ff47fea8e5c528c497fc385c95887131c4319a3411814ba9a766b66a9367/matplotlib-2.2.3-cp37-cp37m-manylinux1_x86_64.whl (12.6MB)
Collecting numpy==1.15.1 (from yape)
  Downloading https://files.pythonhosted.org/packages/1a/2e/4e298c92b1fced64a4414ada9af3253a91083b92b131c2b10c057c507982/numpy-1.15.1-cp37-cp37m-manylinux1_x86_64.whl (13.8MB)
Collecting pandas==0.23.4 (from yape)
  Downloading https://files.pythonhosted.org/packages/67/a7/12261a51ac2e7be4c698ca27cbe364ca5f16d64999456ee47ea8c7b44417/pandas-0.23.4-cp37-cp37m-manylinux1_x86_64.whl (8.8MB)
Collecting setuptools_scm==3.1.0 (from yape)
  Downloading https://files.pythonhosted.org/packages/b2/d5/970632917c53a1fb2751f7da8b288d26546f2b113e4321674051fc9f81e4/setuptools_scm-3.1.0-py2.py3-none-any.whl
Collecting gitchangelog>=3.0.4 (from yape)
  Downloading https://files.pythonhosted.org/packages/9d/f9/554f9d1e2031a330148299b81ed7d6d5f1ef8969154384ca4ae8dd403b7a/gitchangelog-3.0.4-py2.py3-none-any.whl (54kB)
Collecting pre-commit>=1.14.4 (from yape)
  Downloading https://files.pythonhosted.org/packages/8f/77/017fd5ae77f999f63d0e524ad16dc732160de37d22786965b5f8b12d800e/pre_commit-1.14.4-py2.py3-none-any.whl (151kB)
**Collecting black>=18 (from yape)
  Could not find a version that satisfies the requirement black>=18 (from yape) (from versions: 18.3a0, 18.3a1, 18.3a2, 18.3a3, 18.3a4, 18.4a0, 18.4a1, 18.4a2, 18.4a3, 18.4a4, 18.5b0, 18.5b1, 18.6b0, 18.6b1, 18.6b2, 18.6b3, 18.6b4, 18.9b0)
No matching distribution found for black>=18 (from yape)
The command '/bin/sh -c pip install -e git+https://github.com/murrayo/yape.git#egg=yape' returned a non-zero code: 1**

**Comment by kazamatzuri** [comment]
seems like the version number needs more precision. I'll add it once I'm back from skiing

**Comment by kazamatzuri** [comment]
fixed in 87c897209880e6038e06d5fe5660eefa75429528
