### ISSUE TITLE
trying to create week long graph

### ISSUE THREAD

**Issue by larrypwilliams** [murrayo/yape#27]
I am trying to create week's long metric graphs based on Iris system performance html files.
I have been able to successfully create a sqlite database file (data.db), but when I try and use yape using that data.db, I get the following error:

sqlite3.OperationalError: no such column: device

Here is the yape command line I am using:
yape --mgstat --vmstat --filedb data.db -a --skip-parse -o testdata/

**Comment by murrayo** [comment]
Hi, this can sometimes happen when there are different columns in mgstat on different days.  This happens. There is no workaround except to not include the day(s) with a different number of columns. Have you tried using `yaspe` instead? https://github.com/murrayo/yaspe
