### ISSUE TITLE
Limit iostat charts to selected disks only

### ISSUE THREAD

**Issue by murrayo** [murrayo/yape#7]
For systems with many disks eg /dev/sdb, sdc, etc and devmapper /dev/dm-0 etc the output can be time consuming and unwieldy to work with. I would like to see a list of disks eg --iostatdisks "sdb sdc dm-0" and only those disks are charted. Still create .csv for all.

**Comment by murrayo** [comment]
I have added a branch with this feature in it; select_disks_for_iostat

**Comment by kazamatzuri** [comment]
i think this is working now?
